

backtests_composer:

  backtests:
    - name: dolar_euro_macd
      display_name: Dolar Euro MACD
      description: Backtesting de la stratégie MACD sur la paire de devises EUR/USD.
      fourward_testing: 0.3
      historical_data:
        - date_start: 2019-01-01
          date_end: 2020-01-01
          timeframe: 1d
        - date_start: 2020-01-01
          date_end: 2021-01-01
          timeframe: 20m
      data_feeds:
        - asset: EURUSD
          source: Oanda
        - asset: EURUSD
          source: AlphaVantage
      strategies:
        - name: BollingerBandsRSI
        - name: BollingerBands

    
    - name: dolar_euro_macd 2
      display_name: Dolar Euro MACD
      description: Backtesting de la stratégie MACD sur la paire de devises EUR/USD.
      fourward_testing: 0.3
      historical_data:
        - date_start: 2019-01-01
          date_end: 2020-01-01
          timeframe: 1d
        - date_start: 2020-01-01
          date_end: 2021-01-01
          timeframe: 20m
      data_feeds:
        - asset: EURUSD
          source: Oanda
        - asset: EURUSD
          source: AlphaVantage
      strategies:
                - name: BollingerBands
