

indicators_composer:
  indicators:
    - name: BollingerBands
      display_name: Bollinger Bands
      description: Un indicateur de volatilité qui trace deux bandes au-dessus et en dessous d'une moyenne mobile.
      parameters:
        window: 20
        num_std: 2

    - name: MACrossover
      display_name: MA Crossover
      description: Un indicateur qui trace deux moyennes mobiles et génère des signaux d'achat et de vente lorsque la moyenne mobile à court terme croise la moyenne mobile à long terme.
      parameters:
        short_window: 50
        long_window: 200

    - name: RSIDivergence
      display_name: RSI Divergence
      description: Un indicateur qui détecte les divergences entre le mouvement des prix et l'indicateur RSI pour anticiper les retournements de marché.
      parameters:
        signal_period: 14
        long_rsi_period: 70
        short_rsi_period: 30

    - name: MACD
      display_name: MACD
      description: Un indicateur qui génère des signaux d'achat et de vente en fonction du croisement entre la ligne MACD et la ligne de signal.
      parameters:
        fast_period: 12
        slow_period: 26
        signal_period: 9

    - name: RSI 
      display_name: RSI
      description: Un indicateur qui mesure la force et la vitesse du mouvement des prix en comparant le prix actuel à son prix de clôture précédent.
      parameters:
        rsi_period: 14
        overbought: 70
        oversold: 30

    - name: StochasticOscillator
      display_name: Stochastic
      description: Un indicateur qui mesure la position du prix par rapport à son plus haut et son plus bas sur une période donnée.
      parameters:
        k_window: 14
        d_window: 3
        oversold: 20
        overbought: 80