strategies:

  - name: BollingerBands
    class_name: BollingerBandsStrategy
    module_path: trading_strategy
    parameters:
      window: 20
      num_std: 2

  - name: MA_Crossover
    class_name: MACrossoverStrategy
    module_path: trading_strategy
    parameters:
      short_window: 50
      long_window: 200

  - name: RSIDivergence
    class_name: RSIDivergenceStrategy
    module_path: trading_strategy
    parameters:
      signal_period: 14
      long_rsi_period: 70
      short_rsi_period: 30
  
  - name: MACD
    class_name: MACDStrategy
    module_path: trading_strategy
    parameters:
      short_window: 12
      long_window: 26
      signal_window: 9

  - name: ATR
    class_name: ATRStrategy
    module_path: trading_strategy
    parameters:
      window: 14

  - name: IchimokuCloud
    class_name: IchimokuCloudStrategy
    module_path: trading_strategy
    parameters:
      conversion_line_period: 9
      base_line_period: 26
      lagging_span_periods: 52
      displacement: 26

  - name: Breakout
    class_name: BreakoutStrategy
    module_path: trading_strategy
    parameters:
      lookback_window: 20
      buy_margin: 0.05
      sell_margin: 0.05

  - name: MAEnvelope
    class_name: MAEnvelopeStrategy
    module_path: trading_strategy
    parameters:
      ma_period: 20
      ma_type: simple
      ma_distance: 0.02

  - name: StochasticOscillator
    class_name: StochasticOscillatorStrategy
    module_path: trading_strategy
    parameters:
      k_window: 14
      d_window: 3
      oversold: 20
      overbought: 80

