strategies:
  - name: Breakout
    class_name: BreakoutStrategy
    module_path: trading_strategy
    parameters:
      lookback_window: 20
      buy_margin: 0.05
      sell_margin: 0.05

  - name: RSIDivergence
    class_name: RSIDivergenceStrategy
    module_path: trading_strategy
    parameters:
      window: 14
      upper_threshold: 70
      lower_threshold: 30
      long_ema_period: 26
      short_ema_period: 12

  - name: MAEnvelope
    class_name: MAEnvelopeStrategy
    module_path: trading_strategy
    parameters:
      ma_period: 20
      ma_type: simple
      ma_distance: 0.02
