
strategies_composer:
  strategies:

    - name: N_SMA_SDStrategy
      display_name: Normalized Moving Average and Standard Deviation
      description: Une stratégie basée sur la moyenne mobile et l'écart type d'une série de prix normalisée, qui génère des signaux d'achat et de vente en fonction des marges spécifiées.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: N_SMA_SD
          parameters:
            window: 20
      long_rules:
        entry:
          action: buy
          conditions:
            - name: Price_Below_Lower_Band
              condition: close < BollingerBands.lband
            - name: RSI_Below_Oversold
              condition: RSI.value < RSI.oversold
        exit:
          action: sell
          conditions:
            - name: Price_Above_Middle_Band
              condition: close > BollingerBands.mavg
            - name: RSI_Above_Middle_Range
              condition: RSI.value > 50
      short_rules:
        entry:
          action: sell
          conditions:
            - name: Price_Above_Upper_Band
              condition: close > BollingerBands.hband
            - name: RSI_Above_Overbought
              condition: RSI.value > RSI.overbought
        exit:
          action: buy
          conditions:
            - name: Price_Below_Middle_Band
              condition: close < BollingerBands.mavg
            - name: RSI_Below_Middle_Range
              condition: RSI.value < 50

    - name: BollingerBandsRSI
      display_name: Bollinger Bands + RSI
      description: Une stratégie basée sur les bandes de Bollinger, qui utilise un indicateur de volatilité pour identifier les situations de surachat et de survente.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: BollingerBands
          parameters:
            window: 20
            num_std: 2
        - name: RSI 
          parameters:
            rsi_period: 14
            overbought: 70
            oversold: 30
      long_rules:
        entry:
          action: buy
          conditions:
            - name: Price_Below_Lower_Band
              condition: close < BollingerBands.lband
            - name: RSI_Below_Oversold
              condition: RSI.value < RSI.oversold
        exit:
          action: sell
          conditions:
            - name: Price_Above_Middle_Band
              condition: close > BollingerBands.mavg
            - name: RSI_Above_Middle_Range
              condition: RSI.value > 50
      short_rules:
        entry:
          action: sell
          conditions:
            - name: Price_Above_Upper_Band
              condition: close > BollingerBands.hband
            - name: RSI_Above_Overbought
              condition: RSI.value > RSI.overbought
        exit:
          action: buy
          conditions:
            - name: Price_Below_Middle_Band
              condition: close < BollingerBands.mavg
            - name: RSI_Below_Middle_Range
              condition: RSI.value < 50

    - name: BollingerBands
      display_name: Bollinger Bands
      description: Une stratégie basée sur les bandes de Bollinger, qui utilise un indicateur de volatilité pour identifier les situations de surachat et de survente.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: BollingerBands
          parameters:
            window: 20
            num_std: 2
        - name: RSI 
          parameters:
            rsi_period: 14
            overbought: 70
            oversold: 30
      long_rules:
        entry:
          action: buy
          conditions:
            - name: Price_Below_Lower_Band
              condition: close < BollingerBands.lband
        exit:
          action: sell
          conditions:
            - name: Price_Above_Middle_Band
              condition: close > BollingerBands.mavg
      short_rules:
        entry:
          action: sell
          conditions:
            - name: Price_Above_Upper_Band
              condition: close > BollingerBands.hband
        exit:
          action: buy
          conditions:
            - name: Price_Below_Middle_Band
              condition: close < BollingerBands.mavg

    - name: RSIStrategy
      display_name: RSI
      description: Une stratégie basée sur l'indicateur Relative Strength Index (RSI), qui génère des signaux d'achat et de vente en fonction des niveaux de surachat et de survente identifiés par l'indicateur.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: RSI
          parameters:
            rsi_period: 14
            overbought: 70
            oversold: 30
      long_rules:
        entry:
          action: buy
          conditions:
            - name: RSI_Below_Oversold
              condition: RSI.value < RSI.oversold
        exit:
          action: sell
          conditions:
            - name: RSI_Above_Middle_Range
              condition: RSI.value > 50
      short_rules:
        entry:
          action: sell
          conditions:
            - name: RSI_Above_Overbought
              condition: RSI.value > RSI.overbought
        exit:
          action: buy
          conditions:
            - name: RSI_Below_Middle_Range
              condition: RSI.value < 50


    - name: MA_Crossover
      display_name: MA Crossover
      description: Une stratégie de croisement de moyennes mobiles, qui génère des signaux d'achat et de vente lorsque la moyenne mobile à court terme croise la moyenne mobile à long terme.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: MACrossover
          parameters:
            short_window: 50
            long_window: 200
        - name: BollingerBands
          parameters:
            window: 20
            num_std: 2
      long_rules:
        entry:
          action: buy
          conditions:
            - name: MACrossover_Up
              condition: MACrossover.short > MACrossover.long
            - name: Price_Above_Upper_Band
              condition: price > BollingerBands.upper
        exit:
          action: sell
          conditions:
            - name: MACrossover_Down
              condition: MACrossover.short < MACrossover.long
      short_rules:
        entry:
          action: sell
          conditions:
            - name: MACrossover_Down
              condition: MACrossover.short < MACrossover.long
            - name: Price_Below_Lower_Band
              condition: price < BollingerBands.lower
        exit:
          action: buy
          conditions:
            - name: MACrossover_Up
              condition: MACrossover.short > MACrossover.long


    - name: RSIDivergence
      display_name: RSI Divergence
      description: Une stratégie basée sur la divergence de l'indice de force relative (RSI), qui détecte les divergences entre le mouvement des prix et l'indicateur RSI pour anticiper les retournements de marché.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: RSIDivergence
          parameters:
            signal_period: 14
            long_rsi_period: 70
            short_rsi_period: 30
        - name: MACrossover
          parameters:
            short_window: 50
            long_window: 200 
      long_rules:
        entry:
          action: buy
          conditions:
            - name: RSIDivergence_Bullish
              condition: RSIDivergence.divergence == "bullish"
            - name: MACrossover_Up
              condition: MACrossover.short > MACrossover.long
        exit:
          action: sell
          conditions:
            - name: RSIDivergence_Bearish
              condition: RSIDivergence.divergence == "bearish"
      short_rules:
        entry:
          action: sell
          conditions:
            - name: RSIDivergence_Bearish
              condition: RSIDivergence.divergence == "bearish"
            - name: MACrossover_Down
              condition: MACrossover.short < MACrossover.long
        exit:
          action: buy
          conditions:
            - name: RSIDivergence_Bullish
              condition: RSIDivergence.divergence == "bullish"

        

    - name: MACD
      display_name: MACD
      description: Une stratégie basée sur la convergence/divergence des moyennes mobiles (MACD), qui génère des signaux d'achat et de vente en fonction du croisement entre la ligne MACD et la ligne de signal.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: MACD
          parameters:
            short_window: 12
            long_window: 26
            signal_window: 9
      long_rules:
        entry:
          action: buy
          conditions:
            - name: MACD_Crossover_Up
              condition: MACD.line > MACD.signal
        exit:
          action: sell
          conditions:
            - name: MACD_Crossover_Down
              condition: MACD.line < MACD.signal
      short_rules:
        entry:
          action: sell
          conditions:
            - name: MACD_Crossover_Down
              condition: MACD.line < MACD.signal
        exit:
          action: buy
          conditions:
            - name: MACD_Crossover_Up
              condition: MACD.line > MACD.signal


    - name: ATR
      display_name: ATR
      description: Une stratégie basée sur l'indicateur Average True Range (ATR), qui utilise la volatilité pour déterminer les niveaux de stop-loss et de prise de bénéfices.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: ATR
          parameters:
            window: 14
      long_rules:
        entry:
          action: buy
          conditions:
            - name: ATR_Breakout_Up
              condition: price > (price + ATR.value)
        exit:
          action: sell
          conditions:
            - name: ATR_Breakout_Down
              condition: price < (price - ATR.value)
      short_rules:
        entry:
          action: sell
          conditions:
            - name: ATR_Breakout_Down
              condition: price < (price - ATR.value)
        exit:
          action: buy
          conditions:
            - name: ATR_Breakout_Up
              condition: price > (price + ATR.value)

    - name: IchimokuCloud
      display_name: Ichimoku Cloud
      description: Une stratégie basée sur l'indicateur Ichimoku Kinko Hyo (nuage d'Ichimoku), qui combine plusieurs moyennes mobiles pour identifier la tendance et les niveaux de support/résistance.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: IchimokuCloud
          parameters:
            conversion_line_period: 9
            base_line_period: 26
            lagging_span_periods: 52
            displacement: 26
      long_rules:
        entry:
          action: buy
          conditions:
            - name: Price_Above_Cloud
              condition: price > IchimokuCloud.cloud_top
        exit:
          action: sell
          conditions:
            - name: Price_Below_Cloud
              condition: price < IchimokuCloud.cloud_bottom
      short_rules:
        entry:
          action: sell
          conditions:
            - name: Price_Below_Cloud
              condition: price < IchimokuCloud.cloud_bottom
        exit:
          action: buy
          conditions:
            - name: Price_Above_Cloud
              condition: price > IchimokuCloud.cloud_top


    - name: Breakout
      display_name: Breakout
      description: Une stratégie de rupture, qui identifie les situations où les prix sortent d'une période de consolidation et génère des signaux d'achat et de vente en fonction des marges spécifiées.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: Breakout
          parameters:
            lookback_window: 20
            buy_margin: 0.05
            sell_margin: 0.05
      long_rules:
        entry:
          action: buy
          conditions:
            - name: Breakout_Up
              condition: price > Breakout.high
        exit:
          action: sell
          conditions:
            - name: Breakout_Down
              condition: price < Breakout.low
      short_rules:
        entry:
          action: sell
          conditions:
            - name: Breakout_Down
              condition: price < Breakout.low
        exit:
          action: buy
          conditions:
            - name: Breakout_Up
              condition: price > Breakout.high

    - name: MAEnvelope
      display_name: MA Envelope
      description: Une stratégie basée sur l'enveloppe de moyenne mobile, qui utilise des bandes autour d'une moyenne mobile pour identifier les situations de surachat et de survente.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02
        take_profit: 0.04
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: MAEnvelope
          parameters:
            ma_period: 20
            ma_type: simple
            ma_distance: 0.02
      long_rules:
        entry:
          action: buy
          conditions:
            - name: Price_Above_MA
              condition: price > MAEnvelope.upper
        exit:
          action: sell
          conditions:
            - name: Price_Below_MA
              condition: price < MAEnvelope.lower
      short_rules:
        entry:
          action: sell
          conditions:
            - name: Price_Below_MA
              condition: price < MAEnvelope.lower
        exit:
          action: buy
          conditions:
            - name: Price_Above_MA
              condition: price > MAEnvelope.upper


    - name: StochasticOscillator
      display_name: Stochastic Oscillator
      description: Une stratégie basée sur l'oscillateur stochastique, qui génère des signaux d'achat et de vente en fonction des niveaux de surachat et de survente identifiés par l'indicateur.
      financial_management:
        initial_capital: 10000
        risk_per_trade: 0.02
        stop_loss: 0.02  
        take_profit: 0.04  
      instruments:
        - EURUSD
        - GBPUSD
      indicators:
        - name: StochasticOscillator
          parameters:
            k_window: 14
            d_window: 3
            oversold: 20
            overbought: 80
      long_rules:
        entry:
          action: buy
          conditions:
            - name: StochasticOscillator_Crossover_Up
              condition: StochasticOscillator.k > StochasticOscillator.d and StochasticOscillator.k < StochasticOscillator.oversold
        exit:
          action: sell
          conditions:
            - name: StochasticOscillator_Crossover_Down
              condition: StochasticOscillator.k < StochasticOscillator.d and StochasticOscillator.k > StochasticOscillator.overbought
      short_rules:
        entry:
          action: sell
          conditions:
            - name: StochasticOscillator_Crossover_Down
              condition: StochasticOscillator.k < StochasticOscillator.d and StochasticOscillator.k > StochasticOscillator.overbought
        exit:
          action: buy
          conditions:
            - name: StochasticOscillator_Crossover_Up
              condition: StochasticOscillator.k > StochasticOscillator.d and StochasticOscillator.k < StochasticOscillator.oversold
