
strategies_composer:
  strategies:
    - name: BollingerBands
      display_name: Bollinger Bands
      description: Une stratégie basée sur les bandes de Bollinger, qui utilise un indicateur de volatilité pour identifier les situations de surachat et de survente.
      indicators:
        - name: BollingerBands
          parameters:
            window: 20
            num_std: 2
        - name: RSI 
          parameters:
            rsi_period: 14
            overbought: 70
            oversold: 30

    - name: MA_Crossover
      display_name: MA Crossover
      description: Une stratégie de croisement de moyennes mobiles, qui génère des signaux d'achat et de vente lorsque la moyenne mobile à court terme croise la moyenne mobile à long terme.
      indicators:
        - name: MACrossover
          parameters:
            short_window: 50
            long_window: 200
        - name: BollingerBands
          parameters:
            window: 20
            num_std: 2

    - name: RSIDivergence
      display_name: RSI Divergence
      description: Une stratégie basée sur la divergence de l'indice de force relative (RSI), qui détecte les divergences entre le mouvement des prix et l'indicateur RSI pour anticiper les retournements de marché.
      indicators:
        - name: RSIDivergence
          parameters:
            signal_period: 14
            long_rsi_period: 70
            short_rsi_period: 30
        - name: MACrossover
          parameters:
            short_window: 50
            long_window: 200 
    
    - name: MACD
      display_name: MACD
      description: Une stratégie basée sur la convergence/divergence des moyennes mobiles (MACD), qui génère des signaux d'achat et de vente en fonction du croisement entre la ligne MACD et la ligne de signal.
      indicators:
        - name: MACD
          parameters:
            short_window: 12
            long_window: 26
            signal_window: 9

    - name: ATR
      display_name: ATR
      description: Une stratégie basée sur l'indicateur Average True Range (ATR), qui utilise la volatilité pour déterminer les niveaux de stop-loss et de prise de bénéfices.
      indicators:
        - name: ATR
          parameters:
            window: 14

    - name: IchimokuCloud
      display_name: Ichimoku Cloud
      description: Une stratégie basée sur l'indicateur Ichimoku Kinko Hyo (nuage d'Ichimoku), qui combine plusieurs moyennes mobiles pour identifier la tendance et les niveaux de support/résistance.
      indicators:
        - name: IchimokuCloud
          parameters:
            conversion_line_period: 9
            base_line_period: 26
            lagging_span_periods: 52
            displacement: 26

    - name: Breakout
      display_name: Breakout
      description: Une stratégie de rupture, qui identifie les situations où les prix sortent d'une période de consolidation et génère des signaux d'achat et de vente en fonction des marges spécifiées.
      indicators:
        - name: Breakout
          parameters:
            lookback_window: 20
            buy_margin: 0.05
            sell_margin: 0.05

    - name: MAEnvelope
      display_name: MA Envelope
      description: Une stratégie basée sur l'enveloppe de moyenne mobile, qui utilise des bandes autour d'une moyenne mobile pour identifier les situations de surachat et de survente.
      indicators:
        - name: MAEnvelope
          parameters:
            ma_period: 20
            ma_type: simple
            ma_distance: 0.02

    - name: StochasticOscillator
      display_name: Stochastic Oscillator
      description: Une stratégie basée sur l'oscillateur stochastique, qui génère des signaux d'achat et de vente en fonction des niveaux de surachat et de survente identifiés par l'indicateur.
      indicators:
        - name: StochasticOscillator
          parameters:
            k_window: 14
            d_window: 3
            oversold: 20
            overbought: 80
